# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 08:17
from __future__ import unicode_literals

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
